repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args:
            - --fix=lf
    -   id: end-of-file-fixer
