---
  - name: Install python3, python module docker
    hosts: all
    become: true
    gather_facts: yes
    remote_user: ubuntu
    tasks:
      - name: Install python3
        become: true
        apt:
          update_cache: yes
          cache_valid_time: 86400 #One day
          name:
            - python3
            - python3-pip
          state: present
      - name: Install python docker packages
        pip:
          state: present
          name: docker
