version: '3'
services:
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    volumes:
      - type: bind
        source: ./ui
        target: /app
        read_only: true
    command: ["puma", "--debug", "-w 2"]

  post:
    build: ./post-py
    volumes:
      - type: bind
        source: ./post-py
        target: /app
        read_only: true

  comment:
    build: ./comment
    volumes:
      - type: bind
        source: ./comment
        target: /app
        read_only: true
